<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Carla Martínez, Patricia Mateu i Margalida Verd">

<title>Práctica 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Práctica1_files/libs/clipboard/clipboard.min.js"></script>
<script src="Práctica1_files/libs/quarto-html/quarto.js"></script>
<script src="Práctica1_files/libs/quarto-html/popper.min.js"></script>
<script src="Práctica1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Práctica1_files/libs/quarto-html/anchor.min.js"></script>
<link href="Práctica1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Práctica1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Práctica1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Práctica1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Práctica1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#datos-demográficos" id="toc-datos-demográficos" class="nav-link active" data-scroll-target="#datos-demográficos">Datos demográficos</a></li>
  <li><a href="#estudio-por-especie" id="toc-estudio-por-especie" class="nav-link" data-scroll-target="#estudio-por-especie">Estudio por especie</a></li>
  <li><a href="#estudio-por-sexo" id="toc-estudio-por-sexo" class="nav-link" data-scroll-target="#estudio-por-sexo">Estudio por sexo</a></li>
  <li><a href="#estudio-por-año-de-registro" id="toc-estudio-por-año-de-registro" class="nav-link" data-scroll-target="#estudio-por-año-de-registro">Estudio por año de registro</a></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión">Conclusión</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Práctica 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Carla Martínez, Patricia Mateu i Margalida Verd </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Hola cucas, a ver en principio esta echo, lo que me he hecho un poco la picha un lio con el tema de los nombres de los data frames, os hago un resumen, y si se os ocurren nombre mejores (que es lo más probable, pq los mios resultan traumáticos) me decis y los cambio. Un besote xoxos.</p>
<p>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! pinguinos ### data frame original pinguinos_sin_filas_NA_por_todo ### data frame sin las dos filas que tinen NA por todo —–&gt; i.e fila 4 y 272 ;) pinguinos_sin_NA ### data frame sin ningun NA —–&gt; i.e le he aplicado la función na.omit() ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡</p>
<p>Aquí dejamos la dirección de nuestro repositorio Github: https://github.com/MargalidaVerd/Practica1.git</p>
<p>Primero instalamos el paquete <code>palmerpenguins</code> y mostramos por pantalla las primeras filas para asegurarnos que se ha cargado correctamente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 8
   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
   &lt;fct&gt;   &lt;fct&gt;              &lt;dbl&gt;         &lt;dbl&gt;             &lt;int&gt;       &lt;int&gt;
 1 Adelie  Torgersen           39.1          18.7               181        3750
 2 Adelie  Torgersen           39.5          17.4               186        3800
 3 Adelie  Torgersen           40.3          18                 195        3250
 4 Adelie  Torgersen           NA            NA                  NA          NA
 5 Adelie  Torgersen           36.7          19.3               193        3450
 6 Adelie  Torgersen           39.3          20.6               190        3650
 7 Adelie  Torgersen           38.9          17.8               181        3625
 8 Adelie  Torgersen           39.2          19.6               195        4675
 9 Adelie  Torgersen           34.1          18.1               193        3475
10 Adelie  Torgersen           42            20.2               190        4250
# ℹ 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
</div>
</div>
<p>Veamos su estructura:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
 $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
 $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
 $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...</code></pre>
</div>
</div>
<p>Observemos que la variable <code>year</code> es considerada un número pero no nos aporta información numérica sino que es más un factor a tener en cuenta como dato y no como número. Así pues, vamos a considerarla un factor:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
 $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
 $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
 $ year             : Factor w/ 3 levels "2007","2008",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Como podemos observar, el tamaño de la muestra realizada es de 344 pingüinos, de los que se han tomado datos de 8 variables diferentes. Entre estas encontramos tres variables de tipo <em>factor</em>: <code>species</code>, que puede tomar tres valores (“Adelie”, “Chinstrap”, “Gentoo”); la variable <code>island</code>, que asigna la isla de procedencia de cada individuo y toma tres valores también, que son “Biscoe”, “Dream” y “Torgersen”; finalmente los niveles de la variable <code>sex</code> son “female” y “male”, y <code>year</code>, que se atribuye al año de estudio de cada pingüino (2007, 2008 o 2009).</p>
<p>También encontramos dos variables del tipo <em>numérico</em>, que son <code>bill_length_mm</code>, que corresponde a la longitud del pico de cada pingüino, en milímetros, y <code>bill_depth_mm</code>, que corresponde al grosor del pico, también en milímetros.</p>
<p>Finalmente, tenemos tres últimas variables de tipo <em>integer</em>: <code>flipper_length_mm</code>, que corresponde a la longitud de las aletas de cada pingüino, en milímetros, y <code>body_mass_g</code>, que recoge la masa corporal en gramos de cada individuo.</p>
<p>Observamos también que hay valores NA, sin embargo, solo descartaremos a dichos sujetos en el caso en que esto nos afecte al estudio de los datos. Veamos pues, cuales son las muestras que contienen algun valor NA:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 8
   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
   &lt;fct&gt;   &lt;fct&gt;              &lt;dbl&gt;         &lt;dbl&gt;             &lt;int&gt;       &lt;int&gt;
 1 Adelie  Torgersen           NA            NA                  NA          NA
 2 Adelie  Torgersen           34.1          18.1               193        3475
 3 Adelie  Torgersen           42            20.2               190        4250
 4 Adelie  Torgersen           37.8          17.1               186        3300
 5 Adelie  Torgersen           37.8          17.3               180        3700
 6 Adelie  Dream               37.5          18.9               179        2975
 7 Gentoo  Biscoe              44.5          14.3               216        4100
 8 Gentoo  Biscoe              46.2          14.4               214        4650
 9 Gentoo  Biscoe              47.3          13.8               216        4725
10 Gentoo  Biscoe              44.5          15.7               217        4875
11 Gentoo  Biscoe              NA            NA                  NA          NA
# ℹ 2 more variables: sex &lt;fct&gt;, year &lt;fct&gt;</code></pre>
</div>
</div>
<p>Observamos que tenemos dos pinguinos de los que tan sólo sabemos la isla y el año en que se les fué tomada la muestra. Sin embargo, de el resto de pinguinos, los valores NA vienen asociados a la variable sexo. Por lo tanto, a la hora de descartar dichas muestras , lo haremos en función de la variable que estemos estudiando.</p>
<p>Así pues, trabajaremos con el data frame original siempre que no indiquemos lo contrario.</p>
<section id="datos-demográficos" class="level2">
<h2 class="anchored" data-anchor-id="datos-demográficos">Datos demográficos</h2>
<p>Primero de todo, vamos a hacer un análisis de los datos básicos de la muestra, para familiarizarnos con ellos y poder estudiarlos con detalle más adelante. Empecemos por las especies de pingüinos. Recordemos que hay tres:</p>
<ul>
<li><p>“Adelie”</p></li>
<li><p>“Chinstrap”</p></li>
<li><p>“Gentoo”</p></li>
</ul>
<p>Veamos sus frecuencias relativas:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   Adelie Chinstrap    Gentoo 
      152        68       124 </code></pre>
</div>
</div>
<p>Con cierta diferencia, la especie más poblada es la <em>Adelie</em>, seguida de <em>Gentoo</em> y, finalmente, <em>Chinstrap</em>.</p>
<p>También es interesante estudiar la población por islas. A continuación lo vemos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   Biscoe     Dream Torgersen 
      168       124        52 </code></pre>
</div>
</div>
<p>Como podemos ver, la isla más poblada es la de <em>Biscoe</em>, seguida de <em>Dream</em> y, por último, ya más alejada en cuanto a valores, la isla <em>Torgersen</em>.</p>
<p>Analicemos ahora la población de cada isla por especies; es decir, nos interesa ilustrar la cantidad de pingüinos de cada especie en cada isla. En el siguiente gráfico vemos como la especie <em>Adelie</em> se haya en las tres islas, mientras que las otras dos solo en una de ellas.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Práctica1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Un dato también a tener en cuenta en nuestro AED es el año de estudio de los individuos. Visualicemos el recuento:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
2007 2008 2009 
 110  114  120 </code></pre>
</div>
</div>
<p>El tamaño de las muestras de cada año no fluctua significativamente.</p>
<p>Finalmente, veamos el sexo de los individuos de la muestra. Observamos, que ahora si que debemos tener en cuenta los valores NA, por lo tanto, ahora trabajaremos con el data frame que omite todas las filas que contienen algun valor NA.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>tibble [333 × 8] (S3: tbl_df/tbl/data.frame)
 $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_length_mm   : num [1:333] 39.1 39.5 40.3 36.7 39.3 38.9 39.2 41.1 38.6 34.6 ...
 $ bill_depth_mm    : num [1:333] 18.7 17.4 18 19.3 20.6 17.8 19.6 17.6 21.2 21.1 ...
 $ flipper_length_mm: int [1:333] 181 186 195 193 190 181 195 182 191 198 ...
 $ body_mass_g      : int [1:333] 3750 3800 3250 3450 3650 3625 4675 3200 3800 4400 ...
 $ sex              : Factor w/ 2 levels "female","male": 2 1 1 1 2 1 2 1 2 2 ...
 $ year             : Factor w/ 3 levels "2007","2008",..: 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "na.action")= 'omit' Named int [1:11] 4 9 10 11 12 48 179 219 257 269 ...
  ..- attr(*, "names")= chr [1:11] "4" "9" "10" "11" ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt; table of extent 0 &gt;</code></pre>
</div>
</div>
<p>No notamos mucha diferencia entre machos y hembras, por lo que se podrá estudiar más adelante si existen diferencias en las características de los pingüinos en función del sexo cromosómico de estos.</p>
</section>
<section id="estudio-por-especie" class="level2">
<h2 class="anchored" data-anchor-id="estudio-por-especie">Estudio por especie</h2>
<p>Vamos a analizar las diferentes característcas de cada especie. En primer lugar, estudiaremos la media de las caracerísticas de los pingüinos. Lo haremos con la función <code>aggregate()</code>, donde definiremos las características como vector y lo relacionaremos con las diferentes especies de nuestro dataframe. Observamos que ahora si que nos afectan las dos muestras que presentan valores NA en todas las variables, por lo tanto, trabajaremos con el data frame que omite a estos dos sujetos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    species bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1    Adelie       38.79139      18.34636          189.9536    3700.662
2 Chinstrap       48.83382      18.42059          195.8235    3733.088
3    Gentoo       47.50488      14.98211          217.1870    5076.016</code></pre>
</div>
</div>
<p>Como podemos observar, la especie <em>Chinstrap</em> es la que tiene el pico más largo y ancho en comparación a las medias de las otras dos especies. En cambio, la especie <em>Gentoo</em> tiene las aletas más largas que las otras dos especies que están bastante cerca en realción a la media. Y, por último, la especie <em>Gentoo</em> tiene el peso medio considerablemente más alto que las demás que son bastante próximas numéricamente.</p>
<p>Además nos interesa ver cuales son los valores máximos y minimos de cada una de las variables en función de su especie:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    species bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1    Adelie           46.0          21.5               210        4775
2 Chinstrap           58.0          20.8               212        4800
3    Gentoo           59.6          17.3               231        6300</code></pre>
</div>
</div>
<p>Observamos que los pinguinos que presentan los valores máximos de peso corporal, longitud del pico y del ala son todos de la especie <em>Gentoo</em>, notemos que en el caso de la masa corporal la diferencia es significativa en cuanto al resto de especies, mientras que en el grosor del pico el valor máximo viene dado por la especie <em>Chinstrap</em>. Notemos que el valor máximo del grosor del pico de la especie <em>Gentoo</em>, es menor que los valores máximos de las especies <em>Chinstrap</em> y <em>Adelie</em>.</p>
<p>Veamos que ocurre con los valores mínimos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    species bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1    Adelie           32.1          15.5               172        2850
2 Chinstrap           40.9          16.4               178        2700
3    Gentoo           40.9          13.1               203        3950</code></pre>
</div>
</div>
<p>En este caso, los pinguinos <em>Adelie</em>, son los que presentan los valores mínimos tanto de la longitud del pico como la del ala; mientras que en cuanto al grosor del pico nos encontramos con un individuo de especie <em>Gentoo</em>, dato curioso, ya que hemos visto anteriormente que esta especie es la que presenta el valor máximo más pequeño de entre todas las especies. En cuanto al peso corporal, <em>Chinstrap</em> es la especie que presenta el valor mínimo.</p>
<p>Para finalizar este estudio por especies, resumiermos todo lo anterior en los siguientes gráficos:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Práctica1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ahora vamos a estudiar cada especie por separado. Empezaremos estudiando la especie <em>Adelie</em>, que es la más abundante. Vamos a mostrar la media de sus características en relación a la isla que habitan para ver si hay diferencias significativas entre habitar una isla u otra.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1    Biscoe       39.13333      18.25556          189.2889    3727.222
2     Dream       38.50179      18.25179          189.7321    3688.393
3 Torgersen       38.95098      18.42941          191.1961    3706.373</code></pre>
</div>
</div>
<p>Podemos observar que las medias de la largaria y anchura del pico son próximas numéricamente. En cambio, las aletas de los pingüinos <em>Adelie</em> de la isla <em>Torgersen</em> son un poco más largas que las de las otras islas. Sobre el peso podemos decir que las medias son bastante cercanas, así que no notamos diferencias significativas entre el peso de los pingüinos <em>Adelie</em> en referencia a habitar una isla u otra.</p>
<p>Notemos que con las especies <em>Chinstrap</em> y <em>Gentoo</em> no podemos hacer el estudio de las diferentes islas ya que sólo habitan una: la especie <em>Chinstrap</em> habita en <em>Dream</em> y la <em>Gentoo</em> en <em>Biscoe</em>.</p>
</section>
<section id="estudio-por-sexo" class="level2">
<h2 class="anchored" data-anchor-id="estudio-por-sexo">Estudio por sexo</h2>
<p>De nuevo, usaremos el data frame que no contiene ningún valor NA, ya que éste afecta de forma directa al análisis en cuestión.</p>
<p>En esta sección, analizaremos las posibles diferencias entre sexos. Veámoslo de forma sencilla:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     sex bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1 female       42.09697      16.42545          197.3636    3862.273
2   male       45.85476      17.89107          204.5060    4545.685</code></pre>
</div>
</div>
<p>Como se aprecia en la tabla anterior, hay algunas diferencias significativas entre sexos, donde el sexo masculino toma siempre los valores más altos. Cabe destacar la masa corporal: mientras que la media de las hembras ronda los 3900 gramos, la de los machos supera esta cifra en casi 700 gramos.</p>
<p>Fijémonos ahora en los máximos de cada variable:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     sex bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1 female           58.0          20.7               222        5200
2   male           59.6          21.5               231        6300</code></pre>
</div>
</div>
<p>La diferencia más significativa vuelve a ser la de la masa corporal, que difiere en casi 1000 gramos (1kg).</p>
<p>Lo mismo pasa con los valores mínimos, que los mostramos a continuación:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     sex bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1 female           32.1          13.1               172        2700
2   male           34.6          14.1               178        3250</code></pre>
</div>
</div>
</section>
<section id="estudio-por-año-de-registro" class="level2">
<h2 class="anchored" data-anchor-id="estudio-por-año-de-registro">Estudio por año de registro</h2>
<p>Como hemos visto antes, cada año se tomaron datos de, aproximadamente 100 pingüinos. En esta sección analizamos con detalle si existen diferencias en función del año de estudio. Empecemos con las medias, como hemos hecho ya en las dos secciones anteriores:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  year bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1 2007       43.74037      17.42752          196.8807    4124.541
2 2008       43.54123      16.91404          202.7982    4266.667
3 2009       44.45294      17.12521          202.8067    4210.294</code></pre>
</div>
</div>
<p>La variación que más destaca es la media de la longitud de las aletas entre el 2007 y el 2008. Así mismo, en estos mismos años, la masa corporal de los pingüinos aumentó 110 gramos con respecto el año anterior.</p>
</section>
<section id="conclusión" class="level2">
<h2 class="anchored" data-anchor-id="conclusión">Conclusión</h2>
<p>Vamos a ver de manera resumida los datos recogidos anteriormente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      species          island    bill_length_mm  bill_depth_mm  
 Adelie   :146   Biscoe   :163   Min.   :32.10   Min.   :13.10  
 Chinstrap: 68   Dream    :123   1st Qu.:39.50   1st Qu.:15.60  
 Gentoo   :119   Torgersen: 47   Median :44.50   Median :17.30  
                                 Mean   :43.99   Mean   :17.16  
                                 3rd Qu.:48.60   3rd Qu.:18.70  
                                 Max.   :59.60   Max.   :21.50  
 flipper_length_mm  body_mass_g       sex        year    
 Min.   :172       Min.   :2700   female:165   2007:103  
 1st Qu.:190       1st Qu.:3550   male  :168   2008:113  
 Median :197       Median :4050                2009:117  
 Mean   :201       Mean   :4207                          
 3rd Qu.:213       3rd Qu.:4775                          
 Max.   :231       Max.   :6300                          </code></pre>
</div>
</div>
<p>Notemos que el único cálculo que nos faltaría es la deviación típica de las variables numéricas. Para no tener que calcularlas una a una, utilizaremos la librería <code>psych</code> donde tenemos la funcion <code>describe()</code> que nos recoge los datos parecido a como lo haría un summary pero con otro parámetros que nos podrían interesar (la desviación típica entre otros). Por tanto, de la información que nos ofrece cogeremos aquellos que nos interesa investigar, en este caso, la media, la desviación típica, la mediana, el mínimo y el màximo de las variables <code>bill_length_mm</code>, <code>bill_depth_mm</code>,<code>flipper_length_mm</code>, <code>body_mass_g</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mean     sd median trimmed    min    max  skew
bill_length_mm      43.99   5.47   44.5   43.98   32.1   59.6  0.04
bill_depth_mm       17.16   1.97   17.3   17.19   13.1   21.5 -0.15
flipper_length_mm  200.97  14.02  197.0  200.36  172.0  231.0  0.36
body_mass_g       4207.06 805.22 4050.0 4159.46 2700.0 6300.0  0.47</code></pre>
</div>
</div>
<p>Observando los datos que nos da <code>summary()</code>, nos ofrece información ya calculada anteriormente para las variables <code>species</code>, <code>island</code>, <code>sex</code> y <code>year</code>. Vamos a analizar un poco más los datos recogidos en la tabla superior. Primero de todo, vamos a definir cada variable que hemos calculado: <code>mean</code> la media, <code>sd</code> la desviación típica, <code>median</code> la mediana, <code>trimmed</code> la media recortada, <code>min</code> el mínimo, <code>max</code> el máximo y <code>skew</code> el sesgo.</p>
<p>Si comparamos la media recortada (<code>trimmed</code>) con la media general (<code>mean</code>), podemos descubrir cuando los outliers estan sesgando la media con valores extremos. Como podemos ver las medias de las variables son muy próximas numéricamente a la media recortada cosa que nos indica que tenemos pocos o ningún outier en estas variables. Además, en comparación a sus respectivas medianas, también observamos que la distacia ente ellas es mínima.</p>
<p>Por otro lado, la variable <code>skew</code>(sesgo) nos ayuda a ver cuanto sesguegan la media los outliers que pudieran haber. Por tanto, notemos que todos los valores son menores a 1, cosa que nos hacer reafirmar la existencia de ningún o pocos outliers en las variables <code>bill_length_mm</code>, <code>bill_depth_mm</code>,<code>flipper_length_mm</code>, <code>body_mass_g</code>.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>